### ISSUE TITLE
Cant compile this project 

### ISSUE THREAD

**Issue by lectricas** [digitalbuddha/StoreDemo#15]
![errors](https://cloud.githubusercontent.com/assets/8782219/14665798/d3cbb5bc-06e6-11e6-91b9-1376ec48bfb9.png)

**Comment by digitalbuddha** [comment]
Ah sorry. Little copy pasta.will get it updated today

**Comment by digitalbuddha** [comment]
Thank you for reporting, you should be all set. Let me know if any questions.
